/**
 * packet.test.ts — the pure packet layer against fixtures generated by
 * py_tool/gen_fixtures.py from the hardware-verified Python packer.
 *
 * Regenerate with `uv run py_tool/gen_fixtures.py` whenever the Python changes; never
 * hand-edit protocol.json. Run with `npm test` (tsc, then node --test on dist/test).
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";

import {
  ALBUM_CHUNK,
  DYNAMIC_CHUNK,
  HEAD_APP_TO_DEVICE,
  HEAD_DEVICE_TO_APP,
  TYPE,
  checksum,
  fragment,
  framePack,
  fromHex,
  imbContainer,
  isDeviceInfo,
  packJson,
  packet,
  parseNotification,
  parseSize,
  toHex,
} from "../src/protocol/packet.js";

// dist/test/packet.test.js → ../../test/fixtures (fixtures are not compiled, read from source tree)
const here = dirname(fileURLToPath(import.meta.url));
const fixtures = JSON.parse(readFileSync(join(here, "..", "..", "test", "fixtures", "protocol.json"), "utf8")) as Fixtures;

interface Fixtures {
  constants: { HEAD_APP_TO_DEVICE: number; HEAD_DEVICE_TO_APP: number; ALBUM_CHUNK: number; DYNAMIC_CHUNK: number; TYPE: Record<string, number> };
  packet: { name: string; type: number; payload_hex: string; total: number; remaining: number; expected_hex: string }[];
  fragment: { name: string; type: number; blob_hex: string; chunk: number; expected_hex: string[] }[];
  imb: { name: string; jpeg_hex: string; width: number; height: number; expected_hex: string }[];
  framepack: { name: string; jpegs_hex: string[]; width: number; height: number; interval_ms: number; expected_hex: string }[];
  notification: { name: string; raw_hex: string; header_hex: string; text: string; json: Record<string, unknown> | null }[];
}

test("constants match the Python tool", () => {
  assert.equal(HEAD_APP_TO_DEVICE, fixtures.constants.HEAD_APP_TO_DEVICE);
  assert.equal(HEAD_DEVICE_TO_APP, fixtures.constants.HEAD_DEVICE_TO_APP);
  assert.equal(ALBUM_CHUNK, fixtures.constants.ALBUM_CHUNK);
  assert.equal(DYNAMIC_CHUNK, fixtures.constants.DYNAMIC_CHUNK);
  assert.deepEqual({ ...TYPE }, fixtures.constants.TYPE);
});

test("hex helpers round-trip", () => {
  const bytes = Uint8Array.from({ length: 256 }, (_, i) => i);
  assert.equal(toHex(fromHex(toHex(bytes))), toHex(bytes));
  assert.throws(() => fromHex("abc"));
});

test("the brief's canonical vector: {\"type\":7}", () => {
  assert.equal(toHex(packJson(TYPE.VERSION_QUERY, { type: 7 })), "c00700000000000a7b2274797065223a377dc0");
});

for (const f of fixtures.packet) {
  test(`packet: ${f.name}`, () => {
    const got = packet(f.type, fromHex(f.payload_hex), f.total, f.remaining);
    assert.equal(toHex(got), f.expected_hex);
    // every packet sums to zero mod 256
    assert.equal(got.reduce((s, b) => (s + b) & 0xff, 0), 0);
  });
}

test("checksum makes any prefix sum to zero", () => {
  const body = Uint8Array.of(0xc0, 0x06, 0xff, 0xff, 0x01);
  const sum = [...body, checksum(body)].reduce((s, b) => (s + b) & 0xff, 0);
  assert.equal(sum, 0);
});

for (const f of fixtures.fragment) {
  test(`fragment: ${f.name}`, () => {
    const got = fragment(f.type, fromHex(f.blob_hex), f.chunk).map(toHex);
    assert.deepEqual(got, f.expected_hex);
  });
}

test("fragment countdown: first carries total-1, last carries 0, lengths ≤ chunk", () => {
  const blob = new Uint8Array(ALBUM_CHUNK * 3); // + 18 envelope bytes → 4 fragments
  const pkts = fragment(TYPE.ALBUM, blob, ALBUM_CHUNK);
  assert.equal(pkts.length, 4);
  pkts.forEach((p, i) => {
    const v = new DataView(p.buffer, p.byteOffset);
    assert.equal(v.getUint16(2), 4, "total");
    assert.equal(v.getUint16(4), 3 - i, "remaining");
    assert.ok(v.getUint16(6) <= ALBUM_CHUNK, "dataLen");
    assert.equal(p.length, 8 + v.getUint16(6) + 1);
  });
});

for (const f of fixtures.imb) {
  test(`imb: ${f.name}`, () => {
    assert.equal(toHex(imbContainer(fromHex(f.jpeg_hex), f.width, f.height)), f.expected_hex);
  });
}

test("imb header fields decode to what we wrote", () => {
  const jpeg = new Uint8Array(1000);
  const c = imbContainer(jpeg, 368, 368);
  const v = new DataView(c.buffer);
  assert.equal(c.length, 36 + 1000);
  assert.equal(String.fromCharCode(c[0]!, c[1]!, c[2]!), "IMB");
  assert.equal(v.getUint32(8, true), 1032);
  assert.equal(v.getUint16(16, true), 368);
  assert.equal(v.getUint32(24, true), 1000);
});

for (const f of fixtures.framepack) {
  test(`framepack: ${f.name}`, () => {
    assert.equal(toHex(framePack(f.jpegs_hex.map(fromHex), f.width, f.height, f.interval_ms)), f.expected_hex);
  });
}

for (const f of fixtures.notification) {
  test(`notification: ${f.name}`, () => {
    const n = parseNotification(fromHex(f.raw_hex));
    assert.equal(toHex(n.header), f.header_hex);
    assert.equal(n.text, f.text);
    assert.deepEqual(n.json, f.json);
  });
}

test("device info is recognised and its size parsed", () => {
  const n = parseNotification(fromHex(fixtures.notification[0]!.raw_hex));
  assert.ok(isDeviceInfo(n.json));
  assert.deepEqual(parseSize(n.json), { width: 368, height: 368 });
  assert.equal(n.json.time_mode, 1);
  assert.equal(n.json.freespace, 5500);
});
